### ISSUE TITLE
heed help 

### ISSUE THREAD

**Issue by wermaxta** [blueudp/DorkMe#2]
hi i have problem to start DorkMe.py
My OS is Linux kali 4.17.0-kali1-amd64 #1 SMP Debian 4.17.8-1kali1 (2018-07-24) x86_64 GNU/Linux
python -V 
Python 2.7.15

python3 -V 
Python 3.6.6
I git clone https://github.com/blueudp/DorkMe.git
Then i go to the DorkMe dir and i start  pip install -r requirements.txt and i get this error 
pip install -r requirements.txt
Collecting Google-Search-API (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/73/38/eab35d4db8efd12256d30963498afe5210128d3fd221332360de9fc11614/Google-Search-API-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-av8m0_03/Google-Search-API/setup.py", line 15, in <module>
        with open("test_requirements.txt") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'test_requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-av8m0_03/Google-Search-API/

When i start program i get this message
python DorkMe.py --help
Error importing google module, try: pip install Google-Search-API 

I test it with python and python3 is the same result

**Comment by blueudp** [comment]
Hello, what you see is a pip error which has happened to more people, it's like running it with pip3 ... try pip2 install Google-Search-API
